### ISSUE TITLE
example-config shows wrong form for excluded_tables option

### ISSUE THREAD

**Issue by gannicottb** [TonicAI/condenser#10]
From example-config.json
```
"excluded_tables": [
        {"schema": "public","tables": [ "table_of_keys"] }
    ],
```
This does not work, however. The code expects:
```
"excluded_tables": ["schema.table1", "schema.table2", ...]
```
The example-config.json should be updated to be correct. I suspect the example passthrough_tables option is similarly out of date.

**Comment by acolombi** [comment]
Thanks for pointing this out. I've corrected the docs.
