### ISSUE TITLE
Self referential tables are not supported

### ISSUE THREAD

**Issue by jasonjho** [TonicAI/condenser#12]
Seeing 

```ValueError: Circular dependency, public.orders depends on itself!``` 

in cases where tables (e.g. `orders`) have rows with parent references of the same type.

**Comment by acolombi** [comment]
Hi Jason,

Yeah, if you have a circular dependency, you need to instruct Condenser to ignore the dependency. This is accomplished with the `dependency_breaks` part of the config. Judging by the error message I think you'll need to add the following `dependency_breaks`:

```
    "dependency_breaks": [
        {"fk_table": "public.orders", "target_table": "public.orders"},
    ],
```

When do this you're basically telling Condenser to ignore this foreign key for the purposes of subsetting.
