### ISSUE TITLE
Undocumented option

### ISSUE THREAD

**Issue by wankata** [TonicAI/condenser#16]
Hi!

You've got an undocumented option perserve_fk_opportunistically, which is quite important and you've got a typo in the code – it should be preserve_fk_opportunistically instead of perserve_fk_opportunistically.

Please update the documentation to explain the impact and the way of use of that option.

**Comment by acolombi** [comment]
Hi! Unfortunately that option isn't available in our open source implementation, only the commercial license. These two projects do share some code, which is why you see the (admittedly typo-ed) option in this code.
