### ISSUE TITLE
Anonymization support?

### ISSUE THREAD

**Issue by sokoow** [TonicAI/condenser#43]
Great tool, nice work. Is there any chance that this would ever have a basica anonymization/masking implemented like in https://github.com/ankane/pgsync ?

**Comment by yuri-shadunsky** [comment]
Hi -- Glad you like the tool! Condenser is built only for subsetting-only use cases. If you're interested in a tool that does both subsetting and masking, you should take a look at the core Tonic product. We have a free trial and a new [pay as you go](https://www.tonic.ai/blog/tonic-now-offers-a-pay-as-you-go-cloud-based-solution) option that is an easy way to try out the product.
